Update README.md: Add RAX75
jclehner/nmrpflash pull request #160
Opened 2024-11-10 18:20 UTC by ericshu6

Worked to fix the web UI interface on my RAX75. Thanks!

2024-11-10 22:04 UTC, ericshu6 commented
I also changed the code to (supposedly) wait for 60 seconds for an Ethernet connection instead of just 20 seconds. My router didn't boot up in 20 seconds, so I needed to time the command and turning on the router carefully, and I shouldn't have had to do that.

2024-11-22 11:56 UTC, jclehner requested changes
Please see requested change for `nmrp.c`.

2024-11-24 03:18 UTC, ericshu6 commented on nmrp.c
> +		while (!g_interrupted && (time_monotonic() - beg) < 60) {
Done

2024-11-25 07:44 UTC, merged

2024-11-25 07:44 UTC, jclehner commented
Looking good! Thanks!